name: Package and Release Selligent EXTender

on:
  push:
    tags:
      - 'v*' # Se déclenche lors du push d'un tag de version (ex: v1.4)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package Extension (Prod Only)
        run: |
          zip -r selligent-extender.zip ./* -x "README.md" -x ".git*" -x ".github*"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: selligent-extender.zip
          draft: false
          prerelease: false
          name: Selligent EXTender ${{ github.ref_name }}
          body: |
            ## Selligent EXTender ${{ github.ref_name }} (Production)
            
            ### Comment installer ou mettre à jour :
            1. Téléchargez le fichier **`selligent-extender.zip`** ci-dessous.
            2. Extrayez le contenu de l'archive dans votre dossier de travail permanent sur votre ordinateur (ex : `C:\SelligentExtender`).
            3. Référez-vous au guide de mise à jour sur la **[page d'accueil du dépôt GitHub](https://github.com/hugo-rossel/selligent-extender)** pour les instructions pas-à-pas détaillées.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
